#server:
#  port: 8888

#spring:
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: c:/microservice-repo

spring:  
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/fornecedor?useLegacyDatetimeCode=false&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties: 
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
